<?xml version="1.0" ?> 
<!DOCTYPE note [
  <!ELEMENT note (to,from,heading,main)>
  <!ELEMENT to      (#PCDATA)>
  <!ELEMENT from    (#PCDATA)>
  <!ELEMENT heading (#PCDATA)>
  <!ELEMENT main   (#PCDATA)>
]>
<note>
<to>Tove</to>
<from>ali</from>
<heading>Reminder</heading> 
<main>This is message</main>
</note>
