=== Murfy99/web_programing/xml:json/xml+json/sample.dtd
<!ELEMENT note (to+,from,heading*,main)>
<!ELEMENT to      (#PCDATA)>
<!ELEMENT from    (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT main   (#PCDATA)>

=== Murfy99/web_programing/xml:json/xml+json/external-dtd.xml
<?xml version="1.0" ?> 
<!DOCTYPE note SYSTEM "sample.dtd" >
<note>
<to>Ali</to> 
<from>Hasan</from> 
<heading>test</heading>
<heading>test</heading>
<heading>test</heading>
<heading>test</heading>
<heading>test</heading>
<main>This is message</main>
</note>
